= quarkus-security-jdbc

*Demo project for using JDBC based security with Quarkus*

. Setup

.. Dev mode and tests
+
A PostgreSQL database is used for storing users and roles.
It is started as dev service.

.. Prod mode
+
Please provide a PostgreSQL database - see parameters in `application.properties`.

. Demo/test users and roles
+
[cols="1,2,2"]
|===
|User|Password (`Credentials` tab)|Roles (`Role mapping` tab)

|`hugo`
|`hugo_123`
|`demoRole`, `otherRole`, `guest`

|`otto`
|`otto_123`
|`demoRole`, `guest`

|`willi`
|`willi_123`
|`guest`
|===

. Web application
+
The JSF based web application offers public pages (`index.xhtml`, `public/user-info.xhtml`) accessible for everyone without authentication and a private page (`private/user-info.xhtml`) for users with role `demoRole` only. If the latter is requested, the application redirects to `/login.xhtml' for authentication.
+
In case of a login with unsufficient roles (user `willi`) the application just responded with code `403` resulting in a standard browser error page being displayed. Unfortunately none of the attempts to configure a custom error page (Quarkus properties, `web.xml`) succeeded.
+
As workaround `ForbiddenExceptionMapper` is included as REST provider, mapping `403` to a redirect response to `/forbidden.xhtml` in case of a non-REST request.

. REST api
+
`UserInfoResource` publishes these endpoints:
+
[cols="3,2,2"]
|===
|Path|Description|Accessible for

|`/api/user-info/secctx`
|return calling user including roles as JSON object
|everyone

|`/api/user-info/name`
|return current username or `null`, if unauthenticated
|everyone

|`/api/user-info/restricted`
|return `"OK"`
|users with role `demoRole`

|`/api/user-info/restricted2`
|return `"OK"`
|users with role `otherRole`
|===
+
There are tests in `UserInfoResourceTest` for the last 3 endpoints.
+
The REST API uses basic authentication.