# Port
quarkus.http.port=8280

# Logging
quarkus.log.console.darken=1
quarkus.log.console.format=%d{HH:mm:ss,SSS} %-5p [%c{3.}] %s%e%n
quarkus.log.level=WARN
quarkus.log.category."io.quarkus".level=INFO
quarkus.log.category."de.gedoplan.showcase".level=DEBUG

# Persistence
quarkus.hibernate-orm.database.generation=update

# LRA Coordinator (no dev service available yet)
quarkus.lra.coordinator-url=http://localhost:8380/lra-coordinator