# Make log color white background friendly
quarkus:
  log:
    console:
      darken: 1

# Application config
greeting:
  message: Hello
  name: world
  
"%dev":
  greeting:
    name: developer
     
"%test":
  greeting:
    name: tester