= quarkus-kafka

*Demo for reactive messaging with Quarkus and Kafka*

== Environment preconditions

For dev and test profiles a Redpanda test container is used, so a working docker environment is assumed.

When started in prod profile the applications depends on a running Kafka server on `localhost:9092`.

`src/main/docker-compose` contains a Docker compose file for starting this server by running `docker-compose up -f kafka.yaml`.

Please use `Ctrl-C` for stopping Kafka after usage followed by `docker-compose down -f kafka.yaml` for removing the stopped containers.

== Demo applications

. `quarkus-kafka-send` is a Quarkus application for sending `Person` data to the Kafka topic `person`:

* `de.gedoplan.showcase.entity.Person` is a simple class for the data sent.

* `de.gedoplan.showcase.api.PersonResource` forms a rest endpoint `/person` for posting `Person` objects as JSON, e.g.:
+
`curl -d '{"name": "Duck", "firstname": "Donald"}' -H "Content-Type: application/json" -X POST http://localhost:8080/person`
+
For conveniance a `POST` to http://localhost:8080/person/auto (without any data) will auto-generate `Person` objects like `"Warrier, Clone-42"`.
+
The service simply sends the `Person` object into the stream `person`, which is connected to the Kafka topic `person` in `application.properties`.

. `quarkus-kafka-recv` is the counterpart for receiving those `Person` objects:

* `de.gedoplan.showcase.entity.Person` is the same as above.

* `de.gedoplan.showcase.service.PersonReceiver` reads from the Stream `person` and simply logs received `Person` objects to standard out. The stream is connected to the Kafka topic `person` in `application.properties`.

Run the applications with `mvn compile quarkus:dev` in their corresponding project directories.