# Logging
# quarkus.log.console.darken=1
quarkus.log.console.format=%s%e%n
quarkus.log.level=WARN
quarkus.log.category."io.quarkus".level=ERROR
quarkus.log.category."de.gedoplan.showcase".level=DEBUG

quarkus.banner.path=banner.txt

# LRA Coordinator (no dev service available yet)
quarkus.lra.coordinator-url=http://localhost:8380/lra-coordinator

# REST clients
RoomBookingService/mp-rest/url=http://localhost:8180
TrainerBookingService/mp-rest/url=http://localhost:8280
