# Datasource
%prod.quarkus.datasource.jdbc.url=jdbc:mysql://localhost:30306/showcase
%prod.quarkus.datasource.username=showcase
%prod.quarkus.datasource.password=showcase

quarkus.hibernate-orm.database.generation=update

# DB Dev Service
%dev.quarkus.datasource.devservices.port=30306
%dev.quarkus.datasource.devservices.db-name=showcase
%dev.quarkus.datasource.devservices.username=showcase
%dev.quarkus.datasource.devservices.password=showcase

# Logging
quarkus.log.console.enable=true
quarkus.log.console.format=%d{HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n
quarkus.log.console.level=ALL
quarkus.log.console.darken=1

quarkus.log.level=INFO

quarkus.log.category."de.gedoplan".level=DEBUG
quarkus.log.category."de.gedoplan.baselibs".level=INFO
quarkus.log.category."org.hibernate".level=ERROR

