quarkus.datasource.db-kind=h2
%prod.quarkus.datasource.username=gedoplan
%prod.quarkus.datasource.password=gedoplan
%prod.quarkus.datasource.jdbc.url=jdbc:h2:~/h2/quarkus-data-hibernate;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
