<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>de.gedoplan.showcase</groupId>
        <artifactId>quarkus-demo</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>quarkus-qute</artifactId>

    <dependencies>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-arc</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-qute</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkiverse.web-bundler</groupId>
            <artifactId>quarkus-web-bundler</artifactId>
            <version>1.9.1</version>
        </dependency>
        <dependency>
            <groupId>org.webjars.npm</groupId>
            <artifactId>bootstrap</artifactId>
            <version>5.3.7</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.webjars.npm</groupId>
            <artifactId>popperjs__core</artifactId>
            <version>2.11.8</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

</project>
